### ISSUE TITLE
Comments on zbus?

### ISSUE THREAD

**Issue by zeenix** [tmiasko/dbus-core#1]
While you do **not** need any reasons to not use zbus (or zvariant) and writing another D-Bus crate, I was curious if you've any that you'd like to share? When I started working on zbus last year, there was only dbus-rs and I did actually first planned to use it and tried to use it (even contributed actually). Over the last few months, quite a few new D-Bus crates popped up and I'm wondering what could be the reason. Is it just people wanting to do it for the fun (which is a very valid reason too) or is there something wrong with zbus' approach/API that people don't like, or a combination of both maybe?

What about zvariant? It's serde-based so not sure how it can be any better in the Rust world. :)

**Comment by tmiasko** [comment]
The initial work on this crate likely pre-dates zvariant. I am using it together with a crate (not public yet) that offers async D-Bus API with method calls, signals, export of objects, supports object manager, etc. The zvariant / zbus doesn't seem to be a compelling alternative just yet.

I used serde in an early prototype, but concluded that there is no natural mapping between D-Bus data model and serde data model.

It is possible that zvariant came up with a better approach how to integrate the two. I briefly tried to rewrite some of code using it, and don't really know how. The zvariant also lacks examples of things that I would really like to do, e.g., decoding & encoding object properties from `PropertiesChanged` or `GetAll` message while representing those simply as fields inside a struct.  I would expect that doing this through serde will be challenging. The fact that zvariant doesn't seem to have any examples like that, might or might not be a coincidence.

**Comment by zeenix** [comment]
Firstly, thanks for replying and providing the reasons even though you didn't have to at all.

> The initial work on this crate likely pre-dates zvariant.

Ah ok.

> I am using it together with a crate (not public yet) that offers async D-Bus API with method calls, signals, export of objects, supports object manager, etc. The zvariant / zbus doesn't seem to be a compelling alternative just yet.

We're talking now or was it just at the time when you first created it? Although we don't yet have async support, we very much would like to have it and with all the basic (mostly zvariant) work already done and essential sync API already in place (we plan to release zbus  today), it would not be a very big project to add async API.

> I used serde in an early prototype, but concluded that there is no natural mapping between D-Bus data model and serde data model.

I had the exact same struggle but in the end, I made it work, albeit with a small caveat that signature needs to be provided by the user but I manage to make that super trivial and in most cases, user doesn't actually have to do that, thanks to Rust's power of generics and traits.

>  I briefly tried to rewrite some of code using it, and don't really know how.

Yeah, most docs came only some months ago when I released zvariant. But if you had reached out, we could have helped. Missing docs can always be added.

> The zvariant also lacks examples of things that I would really like to do, e.g., decoding & encoding object properties from `PropertiesChanged` or `GetAll` message while representing those simply as fields inside a struct. I would expect that doing this through serde will be challenging.

Actually, `GetAll` [was our test case](https://gitlab.freedesktop.org/zeenix/zbus/-/commit/96092d996db4759a1d0fa655c97769eb3563b544) from the very beginning of the project and we only removed it 3 months ago cause the CI system didn't seem to have that interface for some reason on the D-Bus broker's own Freedesktop interfaces. Because of that not only has the properties interface has always been possible, we now a days have [wrapper API for all Freedesktop standard interface (including properties)](https://gitlab.freedesktop.org/zeenix/zbus/-/blob/master/zbus/src/fdo.rs#L24). A more convenient way is also possible through our [client-side high-level proxy API](https://zeenix.pages.freedesktop.org/zbus/client.html#properties) and server-side is something on our plans for sure.

-----

In any case, if you change your mind about zvariant/zbus, we could really use more help on making it a very awesome project. Oh and I'd **strongly** recommend using zvariant at least. If you don't know how to use it for something, [please reach out](https://gitlab.freedesktop.org/zeenix/zbus/-/tree/master#getting-help) and we'd be happy to help out and add the missing docs.

**Comment by tmiasko** [comment]
> We're talking now or was it just at the time when you first created it?

I am referring to the current state of zbus. From my perspective, using it now would be a step back functionally, most likely not feasible yet.

The [GetAll / GetConnectionCredentials example][0] captures exactly aspect I tried to comment on. The implementation first extract properties into an intermediate representation `HashMap<&str, Variant>`, and then proceeds to extract individual properties out. The intermediate hash map is unfortunate. More importantly, example doesn't use serialize & deserialize impls derived through serde (is it possible to use those?):

```rust
#[derive(Deserialize)
struct Credentials {
  process_id: Option<u32>,
  unix_user_id: Option<u32>,
  unix_group_ids: Option<Vec<u32>>,
  ...
}
```

[0]: https://gitlab.freedesktop.org/zeenix/zbus/-/commit/96092d996db4759a1d0fa655c97769eb3563b544

**Comment by zeenix** [comment]
> I am referring to the current state of zbus. From my perspective, using it now would be a step back functionally, most likely not feasible yet.

I guess it all depends on how far you got. Surely there are things that are missing they could be added and it may or may not be less work than doing your own crate.

> The intermediate hash map is unfortunate

How come? for efficiency reasons (the number of properties have to be huge and complex enough for it to be an issue IMO)? serde is very generic so you can create your own Map type, that skips all other entries but the ones you're interested in.

> More importantly, example doesn't use serialize & deserialize impls derived through serde (is it possible to use those?):

I'm not sure how that will help in this case but yes, if a type implements `serde::de::Deserialize` (whether manually or using the derive macros), you can decode the message body to that type.

**Comment by tmiasko** [comment]
> I'm not sure how that will help in this case but yes, if a type implements `serde::de::Deserialize` (whether manually or using the derive macros), you can decode the message body to that type.

As I mentioned earlier, I don't know how to derive those for object properties to obtain something that works, and neither are there any examples that would do that.

I am going to closing the issue, since it is essentially unrelated to this crate. I you would like to continue our conversation about this or related topics feel free to contact me privately.  

Thanks for comments.

**Comment by elmarco** [comment]
@tmiasko thank you for the great idea about dict to struct mapping. I didn't think of it that way, but I agree 200% with you there. I opened https://gitlab.freedesktop.org/zeenix/zbus/-/issues/56 and will eventually get to it at some point. It should be possible without too much hassle, hopefully.

**Comment by zeenix** [comment]
> [https://gitlab.freedesktop.org/zeenix/zbus/-/issues/56](https://gitlab.freedesktop.org/zeenix/zbus/-/issues/56)

Just to let you know we've now addressed this and the next release of `zvariant` will provide convenient macros for handling Dictionaries the way you wanted to. Sorry, I'm commenting here again but I couldn't find an easy way to get in touch with your privately.
